### ISSUE TITLE
No Output File Is created

### ISSUE THREAD

**Issue by matharotheelf** [KnicKnic/WASM-ImageMagick#81] opened 2020-05-11 19:22 UTC
I am trying to use WASM-ImageMagick but no output seems to be created by my command. 

This is the javascript file where I call 'wasm-imagemagick':

```
import image from "./image.png"
import { buildInputFile, execute, loadImageElement } from 'wasm-imagemagick'

(async () => {
  const { stdout, stderr, exitCode } = await execute({
    inputFiles: [await buildInputFile(image, 'image1.png')],
    commands: 'convert image1.png -rotate 70 image2.png'
  })
  if(exitCode === 0)
      console.log('foo.gif identify output: ' + stdout.join('\n'))
  else
      console.error('foo.gif identify command failed: ' + stderr.join('\n'));

  const maged_img = document.createElement("img")
  maged_img.src = stdout.outputFiles[0]
  console.log(maged_img)
  document.body.appendChild(maged_img)

})();
```
I get the following error in the browser Javascript console: 

```
app.bundle.js:1 Uncaught (in promise) TypeError: Cannot read property '0' of undefined
    at app.bundle.js:1
    at g (polyfill.bundle.js:1)
    at Generator._invoke (polyfill.bundle.js:1)
    at Generator.forEach.t.<computed> [as next] (polyfill.bundle.js:1)
    at i (app.bundle.js:1)
    at s (app.bundle.js:1)
```
 It seems no output file is being produced by my command as `stdout.outputFiles[0]` is raising this error.

This is the only error I get. The `wasm-imagemagick` command seems not to be producing any other error.

I am working with webpack.

I would be thankful for any help!

**Comment by KnicKnic** [comment] 2020-07-29 06:48
I believe this is a dupe of https://github.com/KnicKnic/WASM-ImageMagick/issues/51 closing as such

**Closed by KnicKnic** 2020-07-29 06:48 UTC
